Repository IT-Academy-Social-Projects-KRV/MapUA, pull requests merged in 2022-06, with the labels that each got.

#117 fixed bug - redirect unauthorized user from profile
  frontend/src/components/Profile/Profile.tsx
Labels: bug, fix

#119 fixed bug on change rating && toggle favorite/visited
  backend/controllers/LocationsController.ts
  backend/controllers/UserController.ts
  frontend/src/components/PointPopup/СardComponent/CardComponent.tsx
  frontend/src/redux/actions-creators/popupLocation.tsx
Labels: bug, fix

#120 fixed snackbar invocation in profilePage
  frontend/src/components/Profile/ProfilePage.tsx
Labels: bug, fix

#126 fix (Bozhko bug) show list of subscriptions in filters on mount App
  frontend/src/components/SearchFormContainer/FiltersList/NestedList.tsx
Labels: fix

#129 Fix/snackbar invocation and its localization + redux
  frontend/public/locales/en/translation.json
  frontend/public/locales/ua/translation.json
  frontend/src/App.tsx
  frontend/src/components/CreateLocation/CreateLocation.tsx
  frontend/src/components/ExtendSnackbar/ExtendSnackbar.tsx
  frontend/src/components/ForgotPassword/ForgotPassword.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/components/PointPopup/PointPopup.tsx
  frontend/src/components/Profile/ProfilePage.tsx
  frontend/src/components/Registration/Registration.tsx
  frontend/src/redux/action-types/snackbarActionTypes.ts
  frontend/src/redux/actions-creators/createLocation.ts
  frontend/src/redux/actions-creators/index.tsx
  frontend/src/redux/actions-creators/isUserAuthorized.tsx
  frontend/src/redux/actions-creators/listOfFiltersOptions.ts
  frontend/src/redux/actions-creators/locationComments.tsx
  frontend/src/redux/actions-creators/locationList.tsx
  frontend/src/redux/actions-creators/popupLocation.tsx
  frontend/src/redux/actions-creators/privateUserData.ts
  frontend/src/redux/actions-creators/snackbar.ts
  frontend/src/redux/actions-creators/userData.tsx
  frontend/src/redux/reducers/index.tsx
  frontend/src/redux/reducers/snackbarReducer.ts
  frontend/src/redux/ts-types/index.ts
  frontend/src/static/mainFIlters.tsx
Labels: fix

#132 Fixed ability to add multiple locations
  backend/utils/upload.ts
  frontend/public/locales/en/translation.json
  frontend/public/locales/ua/translation.json
  frontend/src/components/CreateLocation/CreateLocation.tsx
  frontend/src/components/ExtendSnackbar/ExtendSnackbar.tsx
  frontend/src/components/Map/index.tsx
  frontend/src/components/design/BigPopupLocation/index.tsx
  frontend/src/redux/action-types/createLocationActionTypes.ts
  frontend/src/redux/actions-creators/createLocation.ts
  frontend/src/redux/actions-creators/isUserAuthorized.tsx
  frontend/src/redux/actions-creators/snackbar.ts
  frontend/src/redux/actions-creators/userData.tsx
  frontend/src/redux/reducers/createLocationReducer.ts
  frontend/src/screens/HomeScreen.tsx
  frontend/src/utils/validation.ts
Labels: bug

#142 Feature/map 169/subscribe button with logic
  backend/controllers/SubscriptionsController.ts
  backend/locales/en/translation.json
  backend/locales/ua/translation.json
  backend/models/UserModel.ts
  backend/routes/index.ts
  frontend/public/locales/en/translation.json
  frontend/public/locales/ua/translation.json
  frontend/src/components/BigPopup/CommentSection/Comment.tsx
  frontend/src/components/BigPopup/CommentSection/CommentSection.tsx
  frontend/src/components/PersonProfile/PersonProfile.tsx
  frontend/src/components/PersonProfile/PersonProfilePage.tsx
  frontend/src/components/PointPopup/СardComponent/CardComponent.tsx
  frontend/src/components/Profile/BasicTabs.tsx
  frontend/src/components/design/StyledProfile.ts
  frontend/src/redux/actions-creators/userData.tsx
Labels: enhancement, logic, redux, frontEnd

#146 Feature/map 156/map 158/edit personal comment/frontend and backend
  backend/controllers/CommentsController.ts
  backend/locales/en/translation.json
  backend/locales/ua/translation.json
  backend/routes/index.ts
  frontend/public/locales/en/translation.json
  frontend/public/locales/ua/translation.json
  frontend/src/components/BigPopup/CommentSection/Comment.tsx
  frontend/src/components/BigPopup/CommentSection/CommentSection.tsx
  frontend/src/components/BigPopup/CommentSection/EditCommentField.tsx
  frontend/src/components/PointPopup/IconsComponent/IconsComponent.tsx
  frontend/src/components/PointPopup/СardComponent/CardComponent.tsx
  frontend/src/redux/action-types/locationCommentsActionTypes.tsx
  frontend/src/redux/actions-creators/locationComments.tsx
  frontend/src/redux/reducers/locationCommentsReducer.tsx
  frontend/src/utils/validation.ts
  frontend/types.ts
Labels: endpoint, redux, frontEnd

#149 Fixed subscribers logic and deleted empty space in profile
  backend/controllers/SubscriptionsController.ts
  frontend/src/components/PersonProfile/PersonProfile.tsx
Labels: fix

#160 Icons changed to one style/added icons translation stubs
  frontend/public/locales/en/translation.json
  frontend/public/locales/ua/translation.json
  frontend/src/components/BigPopup/CommentSection/Comment.tsx
  frontend/src/components/BigPopup/CommentSection/EditCommentField.tsx
  frontend/src/components/PointPopup/IconsComponent/IconsComponent.tsx
Labels: enhancement
