Repository IT-Academy-Social-Projects-KRV/MapUA, pull requests merged in 2022-05, with the labels that each got.

#25 Feature/map 47/endpoint for personal data
  .vscode/settings.json
  backend/controllers/UserController.ts
  backend/models/Locations.ts
  backend/models/UserModel.ts
  backend/routes/index.ts
  frontend/src/App.tsx
  frontend/src/components/develop/Profile.tsx
  frontend/src/constants/develop.ts
  frontend/types.ts
Labels: enhancement, endpoint

#28 Feature/map 54/add frontend logic to profile page
  backend/controllers/UserController.ts
  backend/routes/index.ts
  frontend/src/App.tsx
  frontend/src/components/Profile/Profile.tsx
  frontend/src/components/develop/Profile.tsx
  frontend/src/redux/actions-creators/user.ts
  frontend/src/redux/components/ComposeComponents.tsx
  frontend/src/redux/components/UserData.tsx
  frontend/src/redux/components/UserList.tsx
  frontend/src/redux/reducers/userReducer.ts
  frontend/src/redux/types/user.ts
Labels: enhancement, endpoint

#32 Feature map 60 create form for find locations
  backend/controllers/LocationsController.ts
  backend/models/Locations.ts
  backend/routes/index.ts
  frontend/src/components/Map/index.tsx
  frontend/src/components/SearchFormContainer/FiltersList/NestedList.tsx
  frontend/src/components/SearchFormContainer/FiltersList/style.ts
  frontend/src/components/SearchFormContainer/SearchForm/index.tsx
  frontend/src/components/SearchFormContainer/SearchForm/style.ts
  frontend/src/components/SearchFormContainer/index.tsx
  frontend/src/components/SearchFormContainer/style.ts
  frontend/src/constants/develop.ts
  frontend/src/redux/actions-creators/index.ts
  frontend/src/redux/actions-creators/locationList.ts
  frontend/src/redux/actions-creators/popupLocation.ts
  frontend/src/redux/actions-creators/todo.ts
  frontend/src/redux/actions-creators/user.ts
  frontend/src/redux/components/ComposeComponents.tsx
  frontend/src/redux/components/TodoList.tsx
  frontend/src/redux/reducers/index.ts
  frontend/src/redux/reducers/locationListReducer.ts
  frontend/src/redux/reducers/popupLocationReducer.ts
  frontend/src/redux/reducers/todoReducer.ts
  frontend/src/redux/reducers/userReducer.ts
  frontend/src/redux/types/locationList.ts
  frontend/src/redux/types/todo.ts
  frontend/src/redux/types/user.ts
  frontend/src/static/mainFIlters.tsx
  frontend/src/utils/requests.ts
  frontend/src/utils/useDebounce.tsx
Labels: enhancement, filters

#39 filter's list items click event improved
  frontend/src/components/SearchFormContainer/FiltersList/NestedList.tsx
Labels: fix

#34 Feat/map 45/create a login page form logic frontend
  frontend/src/App.tsx
  frontend/src/components/Header/NavBar.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/components/Login/styles.ts
  frontend/src/components/Profile/Profile.tsx
  frontend/src/redux/actions-creators/user.ts
  frontend/src/redux/components/UserData.tsx
  frontend/src/redux/reducers/index.ts
  frontend/src/redux/reducers/userLoginReducer.ts
  frontend/src/redux/types/user.ts
  frontend/src/utils/validation.ts
  frontend/yarn.lock
Labels: logic, redux

#51 Fix/map 96/extend location schema
  backend/models/Locations.ts
Labels: duplicate, question, fix

#50 Feat/map 104/endpoint for changing location info
  backend/controllers/LocationsController.ts
  backend/routes/index.ts
  frontend/src/redux/actions-creators/user.ts
Labels: enhancement, endpoint

#55 Fix/location schema
  backend/models/Locations.ts
Labels: fix

#61 Fix/location photo src removal
  frontend/src/components/LocationPopOut/LocationPopOut.tsx
  frontend/src/redux/reducers/popupLocationReducer.tsx
  frontend/src/redux/ts-types/popupLocation.tsx
Labels: fix

#78 Fix/logout handler and profile page form
  frontend/src/components/Profile/BasicTabs.tsx
  frontend/src/components/Profile/ProfilePage.tsx
  frontend/src/screens/HomeScreen.tsx
Labels: fix

#88 language button's styles fix
  frontend/src/components/Header/NavBar.tsx
Labels: enhancement, fix

#90 fixed bug - reload location info on marker hover
  backend/controllers/LocationsController.ts
  frontend/src/components/LocationPopOut/LocationPopOut.tsx
  frontend/src/components/Map/index.tsx
Labels: bug, fix

#92 Changed text to icons in pointpopup location's operations.
  backend/models/Locations.ts
  frontend/src/components/PointPopup/PointPopup.tsx
  frontend/src/redux/reducers/popupLocationReducer.tsx
  frontend/src/redux/ts-types/popupLocation.tsx
Labels: enhancement

#96 fix event handler, reload on add location
  frontend/src/components/CreateLocation/CreateLocation.tsx
Labels: fix
